---
name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [windows-latest]
    if: "!contains(github.event.head_commit.message, '[skip ci]')
    steps:
    - uses: actions/checkout@v1
    - run: create_domain_lists.ps1
      shell: pwsh
    - uses: actions/upload-artifact@v1
      with: 
        name: whitelist
        path: whitelist.txt
    - uses: actions/upload-artifact@v1
      with: 
        name: basic-blacklist
        path: basic-blacklist.txt
    - uses: actions/upload-artifact@v1
      with: 
        name: family-friendly-blacklist
        path: family-friendly-blacklist.txt
    - uses: actions/upload-artifact@v1
      with: 
        name: advanced-blacklist
        path: advanced-blacklist.txt
